services:
  mongodb:
    image: mongo:7
    container_name: educando_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: educando_backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=educando_db
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: educando_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8001
      - PORT=80
    ports:
      - "80:80"

volumes:
  mongodb_data:
  uploads_data:
